services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  # value for database/args/password in data/synapse/homeserver.yaml
      POSTGRES_USER: ${DATABASE_USER}  # value for database/args/user in data/synapse/homeserver.yaml
      POSTGRES_DB: ${DATABASE_NAME}  # value for database/args/databse in data/synapse/homeserver.yaml
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    networks:
      database:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
networks:
  database:
